name: Unity WebGL PR Build

on:
  pull_request:
    branches:
      - main
    paths:
      - "frontend/**"

jobs:
  build-unity-webgl:
    name: Build Unity WebGL (PR)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Cache Unity library
        uses: actions/cache@v3
        with:
          path: frontend/Library
          key: Library-frontend-${{ runner.os }}-${{ hashFiles('frontend/ProjectSettings/**', 'frontend/Packages/**', 'frontend/Assets/**') }}
          restore-keys: |
            Library-frontend-${{ runner.os }}-

      - name: Build Unity project
        uses: game-ci/unity-builder@v4
        id: unity-build
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          BACK_SERVER_URL: ${{ secrets.BACK_SERVER_URL }}
          BACK_SERVER_PORT: ${{ secrets.BACK_SERVER_PORT }}
        with:
          targetPlatform: WebGL
          projectPath: frontend/

      - name: Upload WebGL build artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: unity-webgl-build-output
          path: frontend/Build/WebGL/
          retention-days: 14
