name: Deploy Unity WebGL to DockerHub

on:
  workflow_run:
    workflows: ["Unity WebGL PR Build"]
    types:
      - completed

jobs:
  dockerize-and-deploy:
    name: Dockerize and Deploy WebGL Build
    runs-on: ubuntu-latest
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.pull_requests[0].merged == true &&
      github.event.workflow_run.pull_requests[0].base.ref == 'main'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download WebGL build artifact from PR workflow
        uses: actions/download-artifact@v4
        with:
          name: unity-webgl-build-output
          path: frontend/Build/

      - name: Verify downloaded files (for debugging)
        run: |
          echo "Listing files in frontend/Build/ after download:"
          ls -R frontend/Build/

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: frontend/
          file: frontend/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/mep-frontend:${{ github.event.workflow_run.head_sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/mep-frontend:latest
