name: Manual Main Branch Frontend Build

description: "메인 브랜치에 대해 수동으로 프론트엔드 빌드를 트리거하는 워크플로우입니다."

permissions:
  id-token: write # OIDC 토큰 생성을 위해 필요
  contents: read # 리포지토리 읽기 권한

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "빌드 환경 (예: prod, dev)"
        required: true
        default: "prod"
      ref_name:
        description: "브랜치 이름 (기본값: main)"
        required: false
        default: "main"

jobs:
  call-frontend-build:
    name: Call Reusable Frontend Build
    uses: ./.github/workflows/frontend-build.yml
    with:
      environment: ${{ github.event.inputs.environment }}
      ref_name: ${{ github.event.inputs.ref_name }}
    secrets:
      AWS_INFRA_ROLE_ARN: ${{ secrets.AWS_INFRA_ROLE_ARN }}
