name: Manual Main Branch Backend Build

permissions:
  id-token: write # OIDC 토큰 생성을 위해 필요
  contents: read # 리포지토리 읽기 권한
  packages: write # 패키지 업로드 권한

on:
  workflow_dispatch:
    inputs:
      image_tags:
        description: "게시할 Docker 이미지 태그를 입력하세요. (기본값: main-latest)"
        required: true
        default: "main-latest"

jobs:
  call-reusable-backend-build:
    name: Call Reusable Backend Build
    permissions:
      id-token: write
      contents: read
      packages: write
    uses: ./.github/workflows/backend-build.yml
    with:
      image_tags: ${{ github.event.inputs.image_tags }}
      java_version: "17"
      run_tests: true
      run_security_scan: true
      upload_artifacts: false
      build_context: "manual-main"
      commit_sha: ${{ github.sha }}
      ref_name: "main"
    secrets: inherit
